### ISSUE TITLE
Unzip to folder

### ISSUE THREAD

**Issue by Bengt** [i2p/i2p.i2p#3]
Please unzip to a folder with the project name. E.g. if the installer is run from `~/Downloads/`, unzip to `~/Downloads/i2p/`.

**Comment by silvernode** [comment]
I love making installers, I will make one for i2p and anyone interested in helping can submit pull requests.  I want to try and make the installer as dynamic as possible, which includes getting dependencies per system (as much as can possible be added) such as java. If anyone has any ideas please shoot me a message on github.

I just realized this thread is almost a year old and I replied to it (ouch). I'm sure everyone here will get notified, so let me know what you think of my idea. Thanks

p.s. I have i2p running full time on a dedicated server just to help the network (rarely use it). Keep up the good work.

**Comment by Bengt** [comment]
@silvernode Thanks for commenting. Your idea seems to deserve an issue of its own at least. Perhaps it is even better to have it in an own repository. To make an installer, you need to have nicely organized packages first. This issue is about improving the packaging of this main package. Since no one seems to care, I doubt that an installer for multiple i2p packages is viable at this point.

**Comment by silvernode** [comment]
@Bengt Actually I didn't mean to say installer. I meant to say downloader. Just a script to run that makes sure you have java on your distro and sets everything up before getting the jar and running the install.

**Comment by eyedeekay** [comment]
I'll do this in i2p.firefox.
