### ISSUE TITLE
Releases on GitHub are very old

### ISSUE THREAD

**Issue by Neustradamus** [i2p/i2p.i2p#40]
Dear @i2p team,

Here at right: https://github.com/i2p/i2p.i2p
```
Releases 2
i2p-0.9.15 Latest
on Sep 21, 2014
+ 1 release
```

Can you clean this part (remove releases) because it is not up-to-date and very old:
- https://github.com/i2p/i2p.i2p/releases

Here it is up-to-date:
- https://github.com/i2p/i2p.i2p/tags

Thanks in advance.

**Comment by eyedeekay** [comment]
Until now we haven't officially released to github using their releases architecture, we simply tag at release time. I'll work on a process for this, it shouldn't take too long.

**Comment by eyedeekay** [comment]
Hypothetical shell script which should do it, should be pretty obvious, wanted to show it to somebody before I ran it on the main repo:

```
#! /usr/bin/env sh

if [ ! -d i2p.i2p.git-tags ]; then
    git clone https://github.com/i2p/i2p.i2p i2p.i2p.git-tags
fi
cd i2p.i2p.git-tags || exit
git pull --tags
for crt_tag in $(git tag) 
do
    TAG=$(echo "$crt_tag" | grep '.-.\..\..')
    if [ -n "$TAG" ]; then
        github-release release -u i2p -r i2p.i2p -t "$TAG"
    fi
done
```

**Comment by Neustradamus** [comment]
@eyedeekay: Thanks!
