### ISSUE TITLE
Many sites not accessible with 2.3.0 docker image

### ISSUE THREAD

**Issue by bedaro** [i2p/i2p.i2p#50]
The latest Docker image running 2.3.0-1 is unable to connect to most sites. Planet I2P works fine, but many others, such as notbob and the I2P forum, present an error screen that says "The website was not reachable, because it uses encryption options that are not supported by your I2P or Java version."

It was working under 2.2.0. Because I upgraded I also tested with a fresh config and still get the same error.

**Comment by eyedeekay** [comment]
Please update your docker image to 2.3.0-5 or higher, when this issue which was introduced in 2.3.0-1 was resolved.
