### ISSUE TITLE
multiable SSRF server side request forgery CVE

### ISSUE THREAD

**Issue by coolst3r** [i2p/i2p.i2p#59]
n sanitized input from data from a remote resource flows into openConnection, where it is used as an URL to perform a request. This may result in a Server-Side Request Forgery vulnerability.
‎router/java/src/org/cybergarage/xml/Parser.java:97

‎router/java/src/org/cybergarage/xml/Parser.java:135
‎core/java/src/net/i2p/util/EepGet.java:310
‎router/java/src/org/cybergarage/xml/Parser.java:160

**Comment by eyedeekay** [comment]
Not sure how the tool even came up with this one but it does not appear to be a real bug. Re-open if you can explain differently.
