### ISSUE TITLE
Use of Hardcoded, Security-relevant Constants

### ISSUE THREAD

**Issue by coolst3r** [i2p/i2p.i2p#64]
private static final String PROP_LS_SPK = "i2cp.leaseSetSigningPrivateKey";
    // LS 2
    public static final String PROP_LS_TYPE = "i2cp.leaseSetType";
    private static final String PROP_LS_ENCTYPE = "i2cp.leaseSetEncType";
    private static final String PROP_SECRET = "i2cp.leaseSetSecret";
line:70
Avoid hardcoding values that are meant to be secret. Found hardcoded secret.

core/java/src/net/i2p/client/impl/RequestLeaseSetMessageHandler.java#L70)

**Comment by eyedeekay** [comment]
Not a bug. This is a the name of a property which is stored in a configuration file, format would be `i2cp.leaseSetSecret=secret`. It is not the value of the property, which is the actual secret.
