### ISSUE TITLE
https://deb.i2p2.de not responding

### ISSUE THREAD

**Issue by Pheromon** [i2p/i2p.i2p#72]
I'm sorry to open a bug report here for this kind of problem but I've not found a better way.

It's a few weeks the debian reposository is not accessible, is this a know issue?

**Comment by Pheromon** [comment]
In the meantime, since the debian repository doesn't seem to be fixed, can the .deb be downloaded by hand somewhere else?

**Comment by Ekwen** [comment]
Greetings,

It seems to be a known problem as there is a post on the forum about i2p2.de and i2p2.no subdomains being down.
https://i2pforum.net/viewtopic.php?p=2855
It's from October but I think it's still the same problem as I haven't seen any update on it.

In the meantime the forum post is giving workaround by installing using jar or using ppa repository even for debian.

Cheers

**Comment by Pheromon** [comment]
Thank you for the link, much appreciated.

The problem is that also in the PPA repository the latest packaged version is 2.3 and I wanted to upgrade to 2.4

**Comment by zzzi2p** [comment]
The PPA now has 2.4.0 and our new repo https://deb.i2p.net/ has been announced and also has the new release. @eyedeekay I recommend closing this ticket.

**Comment by Pheromon** [comment]
I verified everything works as expected, thanks for the update
