### ISSUE TITLE
Tag 2.5.2 is missing

### ISSUE THREAD

**Issue by rapenne-s** [i2p/i2p.i2p#78]
There was an announce for a 2.5.2 release on https://geti2p.net/en/blog/post/2024/05/15/2.5.2-Release , in https://geti2p.net/en/download#source github is mentionned as a source to download the sources, but there are no releases/tag for 2.5.2

**Comment by eyedeekay** [comment]
Apologies, I added github release mirroring as a part of our release process when I took over as lead maintainer but I neglected to document it for the backup maintainer. Thanks for the report, I'll fix it in a few minutes.

**Comment by eyedeekay** [comment]
Release is uploaded. In the future it will be mirrored automatically when a tag is pushed.
