### ISSUE TITLE
I2PSnark should set total_size to metadata_size according to BEP09

### ISSUE THREAD

**Issue by mlt** [i2p/i2p.i2p#8]
As of right now, [total_size is just the size of a current piece](https://github.com/i2p/i2p.i2p/blob/master/apps/i2psnark/java/src/org/klomp/snark/ExtensionHandler.java#L300). This [freaks out](https://github.com/arvidn/libtorrent/blob/master/src/ut_metadata.cpp#L588) libtorrent (see arvidn/libtorrent#36). [BEP09](http://www.bittorrent.org/beps/bep_0009.html) says total_size has the same semantics as metadata_size.

**Comment by majestrate** [comment]
i2p uses trac for bug reports, the issue was created at: https://trac.i2p2.de/ticket/1618 (.i2p for within network).

**Comment by aaannndddyyy** [comment]
this has been fixed upstream
