### ISSUE TITLE
Respect for building in Java

### ISSUE THREAD

**Issue by user2745** [i2p/i2p.i2p#80]
It's so wicked what y'all are building, I've been watching for a few years & respect for the immense progress!

Just gonna say, java? (ewww) lol but better than C (eww)

**Comment by zzzi2p** [comment]
thanks, there's also long-stalled Go and Rust router efforts that may get revived soon.
If you'd like to discuss I2P, please find a forum or IRC server, this is not the right place.
@eyedeekay please close this issue.
