### ISSUE TITLE
i2psnark : clear messages button has css issue - light/snark.css:315

### ISSUE THREAD

**Issue by Tunoac** [i2p/i2p.i2p#81]
i2p 2.6.0
Linux, Firefox 128
i2psnark, only light theme

The "clear messages" button is not properly working, only the top ~10% of the button are clickable, the lower 90% of the icon is not clickable.

The issue seems to be here:
**i2psnark/webapps/.resources/themes/light/snark.css:315**
in rule `.snarkMessages li {`

Solution: 
disabling the line 
`     mix-blend-mode: multiply;`
makes the "clear messages" button fully working again.

**Comment by zzzi2p** [comment]
In b0597e32b206aa0a14613b0cab3bc8e12e844e96 to be 2.6.1-3, thank you.

@eyedeekay please close
