### ISSUE TITLE
Transfer failed when installing blizzard-macos plugin from url

### ISSUE THREAD

**Issue by quartermarsh** [i2p/i2p.i2p#87]
eyedeekay I just tried installing from url with: https://github.com/eyedeekay/blizzard/releases/download/nightly/blizzard-macos

Router Log:
`Oct. 5, 2024, 2:59:58 p.m. ERROR [pdate Runner] er.update.ConsoleUpdateManager: Failed net.i2p.router.update.PluginUpdateRunner PLUGIN 714859144610495197 HTTP https://github.com/eyedeekay/blizzard/releases/download/nightly/blizzard-macos for PLUGIN: <b>Failed to download plugin from https://github.com/eyedeekay/blizzard/releases/download/nightly/blizzard-macos</b>`

The side-bar reported similar "Transfer failed..."

Maybe that's not the right url?

I can't think of anything on this end which would be impeding the download. I'm using Firefox esr because the machine is running 10.14.6. (That also means that the java version is not up to date > MacPorts 18.0.2.1 Open JDK Runtime Environment 18.0.2.1 +1)

Sadly, I'm quite uncertain about how I would create a .su file from a downloaded file - except perhaps by doing the old 'change the file extension and see what happens' trick 0_o, which I haven't tried yet. [edit-tried and failed] Any tips there would be appreciated.

**Comment by quartermarsh** [comment]
Ah, I see that I need to figure out how to use makefile.sh with (I assume) the blizzard-macos package on the nightly releases page.
Working on it...

**Comment by quartermarsh** [comment]
Now I have to figure out where to put PLUGINDIR because when I run makeplugin.sh it says I must have plugin directory. I've created a directory named PLUGINDIR in the home folder and the admin user has write permissions but it still doesn't get found by makeplugin.sh so, I wonder what else I need to do. makeplugin.sh is obviously not pointing at that directory - or that directory is not where the script requires it to be. Not to mention that I'm learning on the fly, although I can build and manage standalone snowflake. I'm just missing something here.

**Comment by eyedeekay** [comment]
We should be dealing with this on the blizzard repo with the other similar issues, which will be resolved now that the i2p.i2p release has happened and my plugin keys are updated. Closing this here, please join us at https://github.com/eyedeekay/blizzard/issues instead.
