### ISSUE TITLE
Cleartext Transmission of Sensitive Information

### ISSUE THREAD

**Issue by s-b-repo** [i2p/i2p.i2p#92]
_proxyOut = _proxy.getOutputStream();

Writing to an unencrypted socket is insecure - a man-in-the-middle attacker can tamper the messages. Consider using SSL sockets.

**Comment by s-b-repo** [comment]
/core/java/src/net/i2p/util/EepGet.java#L1440)

**Comment by eyedeekay** [comment]
The described issue(MITM) cannot occur unless the information is actually being transmitted over an unencrypted network. In the section of code you're referencing, eepGet is using a proxy which is hosted locally, on the same computer where eepGet is running, and the data between eepGet and the proxy itself is never transmitted over an unencrypted network. Therefore, the attack you propose cannot occur.

In order for it to occur, the proxy would have to run on one computer, and eepGet would have to run on another. This is not the normal operation of eepGet, and not a thing we recommend people try and do. **IF* a user wants to do it anyway, TLS between the proxy and the client is best left to something like nginx that can run on the same host as the proxy.
